server:
  port: 8090
spring:
  application:
    name: "spring security"
  flyway:
    enabled: true
    schemas: public
    baseline-on-migrate: true
  #    url: jdbc:postgresql://localhost:5432/postgres
  #    user: postgres
  #    password: postgres
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: postgres
    driverClassName: org.postgresql.Driver
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      minimum-idle: 2
      maximum-pool-size: 7
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    properties:
      hibernate:
        format_sql: true

